#!/usr/bin/env python
""" lituus A Python 3.x Magic the Gathering Oracle Parsing and Collation Tool
 for Competitive EDH (cEDH)
Copyright (C) 2019  Temporal Inept (temporalinept@mail.com)

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

Top level directory for lituus program files
Contains:
 /ESoLW report files
 /mtgl parsing and graphing files
 /resources contains AllCards.json and the cEDH database
 /sto contains data files downloaded or generated by lituus
 __init__.py this file
 decklist.py downloads, scrapes and stores cEDH decks from online sources
 mtg.py common paths and constants used by lituus program files
 mtgcard.py defines the MTGCard class - a wrapper around a card dict
 multiverse.py MTGCard generator for all cEDH legal cards in the multiverse
 scrape.py scraper for online decks
"""

#__name__ = 'Lituus'
__license__ = 'GPLv3'
__version__ = '0.1.0'
__date__ = 'May 2019'
__author__ = 'Temporal Inept'
__maintainer__ = 'Temporal Inept'
__email__ = 'temporalinept@mail.com'
__status__ = 'Development'

